# Generated by Django 5.0 on 2024-06-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lens_group_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='lens_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
