# Generated by Django 5.0 on 2024-06-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0002_alter_product_lens_group_id_alter_product_lens_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
