# Generated by Django 5.0 on 2024-06-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0004_review_alter_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
    ]
