# Generated by Django 5.0 on 2024-04-14 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0005_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
