# Generated by Django 5.0 on 2024-07-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0005_remove_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(max_length=300),
        ),
    ]
