# Generated by Django 5.0 on 2024-04-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0007_product_gender_alter_userprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
