# Generated by Django 5.0 on 2024-04-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0009_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
