# Generated by Django 5.0 on 2024-04-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0011_cartitem_quantity_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
