# Generated by Django 5.0 on 2024-05-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0012_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=None, upload_to='users_images/'),
        ),
    ]
