# Generated by Django 5.0 on 2024-05-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0014_product_review_text_product_sentiment_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sentiment',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
