# Generated by Django 5.0 on 2024-05-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0015_alter_review_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
