# Generated by Django 5.0 on 2024-06-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0015_remove_product_review_text_remove_product_sentiment_and_more'),
        ('back_api', '0016_delete_review'),
    ]

    operations = [
    ]
