# Generated by Django 5.0 on 2024-06-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0018_alter_product_gender_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.IntegerField(null=True),
        ),
    ]
