# Generated by Django 5.0 on 2024-06-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0020_product_lens_group_id_product_lens_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lens_group_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lens_id',
        ),
    ]
