# Generated by Django 5.0 on 2024-06-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0022_product_lens_group_id_product_lens_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=10),
        ),
    ]
