# Generated by Django 5.0 on 2024-06-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0023_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
