# Generated by Django 5.0 on 2024-06-16 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0025_productvariation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariation',
        ),
    ]
