# Generated by Django 5.0 on 2024-06-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0026_delete_productvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variations',
            field=models.JSONField(default=list),
        ),
    ]
