# Generated by Django 5.0 on 2024-06-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_api', '0027_product_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variations',
        ),
    ]
